### ISSUE TITLE
Need help with simple build

### ISSUE THREAD

**Issue by donwade** [tttapa/Arduino-Filters#6]
A simple build example would help on your webpage.
Perhaps I'm missing something. Best I could figure out is to go to the scripts directory and run 
$ ./build-arduino-examples.sh
+ ../tools/arduino-example-builder --default-board esp32 --directory ../examples --parallel 8 --jobs 2 --board-options-file ../test/examples-board-options.txt
../tools/arduino-example-builder: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
Now I'm using the latest Ubunutu which has libcrypto.so.1.1.x but 1.0.0 is not offered. I don't think I should have to stand on my head figuring out how to trick Ubunutu to make or install libcrypto  just to get 1.0.0
Any suggestions?

**Comment by tttapa** [comment]
The `build-arduino-examples.sh` script is just meant for continuous integration (it runs when I push any changes so I get notified if I break any examples).

As a user, you just open and build the examples using the Arduino IDE.

**Comment by donwade** [comment]
thanks.
